<?php

namespace AppBundle\Repository;

/**
 * BuyDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BuyDetailRepository extends \Doctrine\ORM\EntityRepository
{
}
