<?php

namespace AppBundle\Repository;

/**
 * IdentificationClassRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IdentificationClassRepository extends \Doctrine\ORM\EntityRepository
{
}
