<?php

namespace AppBundle\Repository;

/**
 * MedicineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MedicineRepository extends \Doctrine\ORM\EntityRepository
{
}
